name: Support new device request
description: suggest the support of a new device
title: 'new device request: <DEVICE NAME>'
labels: 'device-request'

body:
  - type: input
    id: vendor
    attributes:
      label: Device vendor
      description: What's the device vendor?
      placeholder: Google, OnePlus, Sony, ...
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Device model
      description: What's the device model name?
      placeholder: Pixel 7a, 7T Pro, bravia, ...
    validations:
      required: true
  - type: input
    id: codename
    attributes:
      label: Device codename
      description: What's the device codename (if known)?
      placeholder: sunfish, hotdog, ...
    validations:
      required: false
  - type: textarea
    id: los_tree
    attributes:
      label: LineageOS device tree and/or WIKI page
      description: |
        What's the LineageOS URL to the device tree and/or WIKI page (see Notes-1)?
        See https://wiki.lineageos.org/devices for a current list
      value: |
        https://wiki.lineageos.org/devices/<FILL-IN>
    validations:
      required: false
  - type: dropdown
    id: dos_avail
    attributes:
      label: Supported by DivestOS already?
      description: see https://divestos.org/pages/devices for a current list
      options:
        - 'yes'
        - 'no (see Notes-1)'
    validations:
      required: true
  - type: checkboxes
    id: sup_chan
    attributes:
      label: Prepared to support?
      description: I have joined the official AXP.OS [support channel](https://github.com/AXP-OS/build/wiki#support) and willing to provide logs if requested (see Notes-2)
      options:
        - label: "yes, I've joined"
          required: true
  - type: markdown
    attributes:
      value: |
        **Notes**
        
        - _(1) Your request will likely get rejected if there is no official DivestOS and/or LOS reference or if you are not willing/able to provide logs_
        - _(2) Currently not supported devices might get added but this won't work without your help. That means you have to admit to test new builds and maybe provide logs if something is not working as expected._
